apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-eks-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Arsharora0001/react-demo.git
    targetRevision: main
    path: k8s/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
